# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/alpha.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18sandbox/test/alpha.proto\x12\x0csandbox.test\"4\n\x0c\x41lphaMessage\x12\x11\n\tmy_string\x18\x01 \x01(\t\x12\x11\n\tmy_number\x18\x02 \x01(\x05\x62\x06proto3')



_ALPHAMESSAGE = DESCRIPTOR.message_types_by_name['AlphaMessage']
AlphaMessage = _reflection.GeneratedProtocolMessageType('AlphaMessage', (_message.Message,), {
  'DESCRIPTOR' : _ALPHAMESSAGE,
  '__module__' : 'sandbox.test.alpha_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.AlphaMessage)
  })
_sym_db.RegisterMessage(AlphaMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ALPHAMESSAGE._serialized_start=42
  _ALPHAMESSAGE._serialized_end=94
# @@protoc_insertion_point(module_scope)
