# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/anytest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1asandbox/test/anytest.proto\x12\x0csandbox.test\x1a\x19google/protobuf/any.proto\"\xe0\x01\n\nAnyMessage\x12$\n\x06my_any\x18\x01 \x01(\x0b\x32\x14.google.protobuf.Any\x12)\n\x0bmy_any_list\x18\x02 \x03(\x0b\x32\x14.google.protobuf.Any\x12:\n\nmy_any_map\x18\x03 \x03(\x0b\x32&.sandbox.test.AnyMessage.MyAnyMapEntry\x1a\x45\n\rMyAnyMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12#\n\x05value\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any:\x02\x38\x01\x62\x06proto3')



_ANYMESSAGE = DESCRIPTOR.message_types_by_name['AnyMessage']
_ANYMESSAGE_MYANYMAPENTRY = _ANYMESSAGE.nested_types_by_name['MyAnyMapEntry']
AnyMessage = _reflection.GeneratedProtocolMessageType('AnyMessage', (_message.Message,), {

  'MyAnyMapEntry' : _reflection.GeneratedProtocolMessageType('MyAnyMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _ANYMESSAGE_MYANYMAPENTRY,
    '__module__' : 'sandbox.test.anytest_pb2'
    # @@protoc_insertion_point(class_scope:sandbox.test.AnyMessage.MyAnyMapEntry)
    })
  ,
  'DESCRIPTOR' : _ANYMESSAGE,
  '__module__' : 'sandbox.test.anytest_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.AnyMessage)
  })
_sym_db.RegisterMessage(AnyMessage)
_sym_db.RegisterMessage(AnyMessage.MyAnyMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ANYMESSAGE_MYANYMAPENTRY._options = None
  _ANYMESSAGE_MYANYMAPENTRY._serialized_options = b'8\001'
  _ANYMESSAGE._serialized_start=72
  _ANYMESSAGE._serialized_end=296
  _ANYMESSAGE_MYANYMAPENTRY._serialized_start=227
  _ANYMESSAGE_MYANYMAPENTRY._serialized_end=296
# @@protoc_insertion_point(module_scope)
