# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/illnamedfields.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!sandbox/test/illnamedfields.proto\x12\x0csandbox.test\"\x83\x04\n\x08\x42\x61\x64Names\x12\r\n\x05\x46\x61lse\x18\x01 \x01(\t\x12\x0c\n\x04None\x18\x02 \x01(\t\x12\x0c\n\x04True\x18\x03 \x01(\t\x12\x0b\n\x03\x61nd\x18\x04 \x01(\t\x12\n\n\x02\x61s\x18\x05 \x01(\t\x12\x0e\n\x06\x61ssert\x18\x06 \x01(\t\x12\r\n\x05\x61sync\x18\x07 \x01(\t\x12\r\n\x05\x61wait\x18\x08 \x01(\t\x12\r\n\x05\x62reak\x18\t \x01(\t\x12\r\n\x05\x63lass\x18\n \x01(\t\x12\x10\n\x08\x63ontinue\x18\x0b \x01(\t\x12\x0b\n\x03\x64\x65\x66\x18\x0c \x01(\t\x12\x0b\n\x03\x64\x65l\x18\r \x01(\t\x12\x0c\n\x04\x65lif\x18\x0e \x01(\t\x12\x0c\n\x04\x65lse\x18\x0f \x01(\t\x12\x0e\n\x06\x65xcept\x18\x10 \x01(\t\x12\x0f\n\x07\x66inally\x18\x11 \x01(\t\x12\x0b\n\x03\x66or\x18\x12 \x01(\t\x12\x0c\n\x04\x66rom\x18\x13 \x01(\t\x12\x0e\n\x06global\x18\x14 \x01(\t\x12\n\n\x02if\x18\x15 \x01(\t\x12\x0e\n\x06import\x18\x16 \x01(\t\x12\n\n\x02in\x18\x17 \x01(\t\x12\n\n\x02is\x18\x18 \x01(\t\x12\x0e\n\x06lambda\x18\x19 \x01(\t\x12\x10\n\x08nonlocal\x18\x1a \x01(\t\x12\x0b\n\x03not\x18\x1b \x01(\t\x12\n\n\x02or\x18\x1c \x01(\t\x12\x0c\n\x04pass\x18\x1d \x01(\t\x12\r\n\x05raise\x18\x1e \x01(\t\x12\x0e\n\x06return\x18\x1f \x01(\t\x12\x0b\n\x03try\x18  \x01(\t\x12\r\n\x05while\x18! \x01(\t\x12\x0c\n\x04with\x18\" \x01(\t\x12\r\n\x05yield\x18# \x01(\tb\x06proto3')



_BADNAMES = DESCRIPTOR.message_types_by_name['BadNames']
BadNames = _reflection.GeneratedProtocolMessageType('BadNames', (_message.Message,), {
  'DESCRIPTOR' : _BADNAMES,
  '__module__' : 'sandbox.test.illnamedfields_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.BadNames)
  })
_sym_db.RegisterMessage(BadNames)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BADNAMES._serialized_start=52
  _BADNAMES._serialized_end=567
# @@protoc_insertion_point(module_scope)
