# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/illnamedservice.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"sandbox/test/illnamedservice.proto\x12\x0csandbox.test\"\x17\n\x08MyAction\x12\x0b\n\x03\x66oo\x18\x01 \x01(\t\"\x1c\n\rMyConsequence\x12\x0b\n\x03\x62\x61r\x18\x01 \x01(\t2`\n\x1aServiceWithBadRequestNames\x12\x42\n\x0b\x44oSomething\x12\x16.sandbox.test.MyAction\x1a\x1b.sandbox.test.MyConsequenceb\x06proto3')



_MYACTION = DESCRIPTOR.message_types_by_name['MyAction']
_MYCONSEQUENCE = DESCRIPTOR.message_types_by_name['MyConsequence']
MyAction = _reflection.GeneratedProtocolMessageType('MyAction', (_message.Message,), {
  'DESCRIPTOR' : _MYACTION,
  '__module__' : 'sandbox.test.illnamedservice_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.MyAction)
  })
_sym_db.RegisterMessage(MyAction)

MyConsequence = _reflection.GeneratedProtocolMessageType('MyConsequence', (_message.Message,), {
  'DESCRIPTOR' : _MYCONSEQUENCE,
  '__module__' : 'sandbox.test.illnamedservice_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.MyConsequence)
  })
_sym_db.RegisterMessage(MyConsequence)

_SERVICEWITHBADREQUESTNAMES = DESCRIPTOR.services_by_name['ServiceWithBadRequestNames']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MYACTION._serialized_start=52
  _MYACTION._serialized_end=75
  _MYCONSEQUENCE._serialized_start=77
  _MYCONSEQUENCE._serialized_end=105
  _SERVICEWITHBADREQUESTNAMES._serialized_start=107
  _SERVICEWITHBADREQUESTNAMES._serialized_end=203
# @@protoc_insertion_point(module_scope)
