# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from sandbox.test import illnamedservice_pb2 as sandbox_dot_test_dot_illnamedservice__pb2


class ServiceWithBadRequestNamesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DoSomething = channel.unary_unary(
                '/sandbox.test.ServiceWithBadRequestNames/DoSomething',
                request_serializer=sandbox_dot_test_dot_illnamedservice__pb2.MyAction.SerializeToString,
                response_deserializer=sandbox_dot_test_dot_illnamedservice__pb2.MyConsequence.FromString,
                )


class ServiceWithBadRequestNamesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DoSomething(self, request, context):
        """Say hello
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServiceWithBadRequestNamesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DoSomething': grpc.unary_unary_rpc_method_handler(
                    servicer.DoSomething,
                    request_deserializer=sandbox_dot_test_dot_illnamedservice__pb2.MyAction.FromString,
                    response_serializer=sandbox_dot_test_dot_illnamedservice__pb2.MyConsequence.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sandbox.test.ServiceWithBadRequestNames', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServiceWithBadRequestNames(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DoSomething(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sandbox.test.ServiceWithBadRequestNames/DoSomething',
            sandbox_dot_test_dot_illnamedservice__pb2.MyAction.SerializeToString,
            sandbox_dot_test_dot_illnamedservice__pb2.MyConsequence.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
