# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/imported_enum.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sandbox.test import enums_pb2 as sandbox_dot_test_dot_enums__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n sandbox/test/imported_enum.proto\x12\x0csandbox.test\x1a\x18sandbox/test/enums.proto\"O\n\x17MessageWithImportedEnum\x12\x34\n\x10my_external_enum\x18\x01 \x01(\x0e\x32\x1a.sandbox.test.ExternalEnumb\x06proto3')



_MESSAGEWITHIMPORTEDENUM = DESCRIPTOR.message_types_by_name['MessageWithImportedEnum']
MessageWithImportedEnum = _reflection.GeneratedProtocolMessageType('MessageWithImportedEnum', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEWITHIMPORTEDENUM,
  '__module__' : 'sandbox.test.imported_enum_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.MessageWithImportedEnum)
  })
_sym_db.RegisterMessage(MessageWithImportedEnum)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEWITHIMPORTEDENUM._serialized_start=76
  _MESSAGEWITHIMPORTEDENUM._serialized_end=155
# @@protoc_insertion_point(module_scope)
