# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/interfaceonly.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import service as _service
from google.protobuf import service_reflection
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n sandbox/test/interfaceonly.proto\x12\x0csandbox.test\"\"\n\x0eOnHelloRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\" \n\x0fOnHelloResponse\x12\r\n\x05reply\x18\x01 \x01(\t2^\n\x14InterfaceOnlyService\x12\x46\n\x07OnHello\x12\x1c.sandbox.test.OnHelloRequest\x1a\x1d.sandbox.test.OnHelloResponseB\x03\x90\x01\x01\x62\x06proto3')



_ONHELLOREQUEST = DESCRIPTOR.message_types_by_name['OnHelloRequest']
_ONHELLORESPONSE = DESCRIPTOR.message_types_by_name['OnHelloResponse']
OnHelloRequest = _reflection.GeneratedProtocolMessageType('OnHelloRequest', (_message.Message,), {
  'DESCRIPTOR' : _ONHELLOREQUEST,
  '__module__' : 'sandbox.test.interfaceonly_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.OnHelloRequest)
  })
_sym_db.RegisterMessage(OnHelloRequest)

OnHelloResponse = _reflection.GeneratedProtocolMessageType('OnHelloResponse', (_message.Message,), {
  'DESCRIPTOR' : _ONHELLORESPONSE,
  '__module__' : 'sandbox.test.interfaceonly_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.OnHelloResponse)
  })
_sym_db.RegisterMessage(OnHelloResponse)

_INTERFACEONLYSERVICE = DESCRIPTOR.services_by_name['InterfaceOnlyService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\001\001'
  _ONHELLOREQUEST._serialized_start=50
  _ONHELLOREQUEST._serialized_end=84
  _ONHELLORESPONSE._serialized_start=86
  _ONHELLORESPONSE._serialized_end=118
  _INTERFACEONLYSERVICE._serialized_start=120
  _INTERFACEONLYSERVICE._serialized_end=214
InterfaceOnlyService = service_reflection.GeneratedServiceType('InterfaceOnlyService', (_service.Service,), dict(
  DESCRIPTOR = _INTERFACEONLYSERVICE,
  __module__ = 'sandbox.test.interfaceonly_pb2'
  ))

InterfaceOnlyService_Stub = service_reflection.GeneratedServiceStubType('InterfaceOnlyService_Stub', (InterfaceOnlyService,), dict(
  DESCRIPTOR = _INTERFACEONLYSERVICE,
  __module__ = 'sandbox.test.interfaceonly_pb2'
  ))


# @@protoc_insertion_point(module_scope)
