# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/nested.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19sandbox/test/nested.proto\x12\x0csandbox.test\"\xad\x01\n\x0cOuterMessage\x12\x0e\n\x06my_int\x18\x01 \x01(\x05\x12\x11\n\tmy_string\x18\x02 \x01(\t\x12;\n\nmy_message\x18\x03 \x01(\x0b\x32\'.sandbox.test.OuterMessage.InnerMessage\x1a=\n\x0cInnerMessage\x12\x14\n\x0cmy_inner_int\x18\x01 \x01(\x05\x12\x17\n\x0fmy_inner_string\x18\x02 \x01(\tb\x06proto3')



_OUTERMESSAGE = DESCRIPTOR.message_types_by_name['OuterMessage']
_OUTERMESSAGE_INNERMESSAGE = _OUTERMESSAGE.nested_types_by_name['InnerMessage']
OuterMessage = _reflection.GeneratedProtocolMessageType('OuterMessage', (_message.Message,), {

  'InnerMessage' : _reflection.GeneratedProtocolMessageType('InnerMessage', (_message.Message,), {
    'DESCRIPTOR' : _OUTERMESSAGE_INNERMESSAGE,
    '__module__' : 'sandbox.test.nested_pb2'
    # @@protoc_insertion_point(class_scope:sandbox.test.OuterMessage.InnerMessage)
    })
  ,
  'DESCRIPTOR' : _OUTERMESSAGE,
  '__module__' : 'sandbox.test.nested_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.OuterMessage)
  })
_sym_db.RegisterMessage(OuterMessage)
_sym_db.RegisterMessage(OuterMessage.InnerMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OUTERMESSAGE._serialized_start=44
  _OUTERMESSAGE._serialized_end=217
  _OUTERMESSAGE_INNERMESSAGE._serialized_start=156
  _OUTERMESSAGE_INNERMESSAGE._serialized_end=217
# @@protoc_insertion_point(module_scope)
