# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/river.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18sandbox/test/river.proto\x12\x0csandbox.test\"$\n\x14ReverseMyShitRequest\x12\x0c\n\x04shit\x18\x01 \x01(\t\"%\n\x15ReverseMyShitResponse\x12\x0c\n\x04tihs\x18\x01 \x01(\t\"$\n\x13TellMeAStoryRequest\x12\r\n\x05story\x18\x01 \x01(\t\"$\n\x14TellMeAStoryResponse\x12\x0c\n\x04line\x18\x01 \x01(\t\"$\n\x10MarcoPoloRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"#\n\x11MarcoPoloResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\'\n\x15GuessTheNumberRequest\x12\x0e\n\x06number\x18\x01 \x01(\x05\"+\n\x16GuessTheNumberResponse\x12\x11\n\tdid_i_win\x18\x01 \x01(\t2\xf6\x02\n\x10StreamingService\x12X\n\rReverseMyShit\x12\".sandbox.test.ReverseMyShitRequest\x1a#.sandbox.test.ReverseMyShitResponse\x12P\n\tMarcoPolo\x12\x1e.sandbox.test.MarcoPoloRequest\x1a\x1f.sandbox.test.MarcoPoloResponse(\x01\x30\x01\x12W\n\x0cTellMeAStory\x12!.sandbox.test.TellMeAStoryRequest\x1a\".sandbox.test.TellMeAStoryResponse0\x01\x12]\n\x0eGuessTheNumber\x12#.sandbox.test.GuessTheNumberRequest\x1a$.sandbox.test.GuessTheNumberResponse(\x01\x62\x06proto3')



_REVERSEMYSHITREQUEST = DESCRIPTOR.message_types_by_name['ReverseMyShitRequest']
_REVERSEMYSHITRESPONSE = DESCRIPTOR.message_types_by_name['ReverseMyShitResponse']
_TELLMEASTORYREQUEST = DESCRIPTOR.message_types_by_name['TellMeAStoryRequest']
_TELLMEASTORYRESPONSE = DESCRIPTOR.message_types_by_name['TellMeAStoryResponse']
_MARCOPOLOREQUEST = DESCRIPTOR.message_types_by_name['MarcoPoloRequest']
_MARCOPOLORESPONSE = DESCRIPTOR.message_types_by_name['MarcoPoloResponse']
_GUESSTHENUMBERREQUEST = DESCRIPTOR.message_types_by_name['GuessTheNumberRequest']
_GUESSTHENUMBERRESPONSE = DESCRIPTOR.message_types_by_name['GuessTheNumberResponse']
ReverseMyShitRequest = _reflection.GeneratedProtocolMessageType('ReverseMyShitRequest', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEMYSHITREQUEST,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.ReverseMyShitRequest)
  })
_sym_db.RegisterMessage(ReverseMyShitRequest)

ReverseMyShitResponse = _reflection.GeneratedProtocolMessageType('ReverseMyShitResponse', (_message.Message,), {
  'DESCRIPTOR' : _REVERSEMYSHITRESPONSE,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.ReverseMyShitResponse)
  })
_sym_db.RegisterMessage(ReverseMyShitResponse)

TellMeAStoryRequest = _reflection.GeneratedProtocolMessageType('TellMeAStoryRequest', (_message.Message,), {
  'DESCRIPTOR' : _TELLMEASTORYREQUEST,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.TellMeAStoryRequest)
  })
_sym_db.RegisterMessage(TellMeAStoryRequest)

TellMeAStoryResponse = _reflection.GeneratedProtocolMessageType('TellMeAStoryResponse', (_message.Message,), {
  'DESCRIPTOR' : _TELLMEASTORYRESPONSE,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.TellMeAStoryResponse)
  })
_sym_db.RegisterMessage(TellMeAStoryResponse)

MarcoPoloRequest = _reflection.GeneratedProtocolMessageType('MarcoPoloRequest', (_message.Message,), {
  'DESCRIPTOR' : _MARCOPOLOREQUEST,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.MarcoPoloRequest)
  })
_sym_db.RegisterMessage(MarcoPoloRequest)

MarcoPoloResponse = _reflection.GeneratedProtocolMessageType('MarcoPoloResponse', (_message.Message,), {
  'DESCRIPTOR' : _MARCOPOLORESPONSE,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.MarcoPoloResponse)
  })
_sym_db.RegisterMessage(MarcoPoloResponse)

GuessTheNumberRequest = _reflection.GeneratedProtocolMessageType('GuessTheNumberRequest', (_message.Message,), {
  'DESCRIPTOR' : _GUESSTHENUMBERREQUEST,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.GuessTheNumberRequest)
  })
_sym_db.RegisterMessage(GuessTheNumberRequest)

GuessTheNumberResponse = _reflection.GeneratedProtocolMessageType('GuessTheNumberResponse', (_message.Message,), {
  'DESCRIPTOR' : _GUESSTHENUMBERRESPONSE,
  '__module__' : 'sandbox.test.river_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.GuessTheNumberResponse)
  })
_sym_db.RegisterMessage(GuessTheNumberResponse)

_STREAMINGSERVICE = DESCRIPTOR.services_by_name['StreamingService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REVERSEMYSHITREQUEST._serialized_start=42
  _REVERSEMYSHITREQUEST._serialized_end=78
  _REVERSEMYSHITRESPONSE._serialized_start=80
  _REVERSEMYSHITRESPONSE._serialized_end=117
  _TELLMEASTORYREQUEST._serialized_start=119
  _TELLMEASTORYREQUEST._serialized_end=155
  _TELLMEASTORYRESPONSE._serialized_start=157
  _TELLMEASTORYRESPONSE._serialized_end=193
  _MARCOPOLOREQUEST._serialized_start=195
  _MARCOPOLOREQUEST._serialized_end=231
  _MARCOPOLORESPONSE._serialized_start=233
  _MARCOPOLORESPONSE._serialized_end=268
  _GUESSTHENUMBERREQUEST._serialized_start=270
  _GUESSTHENUMBERREQUEST._serialized_end=309
  _GUESSTHENUMBERRESPONSE._serialized_start=311
  _GUESSTHENUMBERRESPONSE._serialized_end=354
  _STREAMINGSERVICE._serialized_start=357
  _STREAMINGSERVICE._serialized_end=731
# @@protoc_insertion_point(module_scope)
