# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/service_with_oneof.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%sandbox/test/service_with_oneof.proto\x12\x0csandbox.test\"%\n\x11HelloAgainRequest\x12\x10\n\x08greeting\x18\x01 \x01(\t\"C\n\x12HelloAgainResponse\x12\x12\n\x08response\x18\x01 \x01(\tH\x00\x12\x10\n\x06number\x18\x02 \x01(\x05H\x00\x42\x07\n\x05reply2e\n\x12SimpleOneOfService\x12O\n\nHelloAgain\x12\x1f.sandbox.test.HelloAgainRequest\x1a .sandbox.test.HelloAgainResponseb\x06proto3')



_HELLOAGAINREQUEST = DESCRIPTOR.message_types_by_name['HelloAgainRequest']
_HELLOAGAINRESPONSE = DESCRIPTOR.message_types_by_name['HelloAgainResponse']
HelloAgainRequest = _reflection.GeneratedProtocolMessageType('HelloAgainRequest', (_message.Message,), {
  'DESCRIPTOR' : _HELLOAGAINREQUEST,
  '__module__' : 'sandbox.test.service_with_oneof_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.HelloAgainRequest)
  })
_sym_db.RegisterMessage(HelloAgainRequest)

HelloAgainResponse = _reflection.GeneratedProtocolMessageType('HelloAgainResponse', (_message.Message,), {
  'DESCRIPTOR' : _HELLOAGAINRESPONSE,
  '__module__' : 'sandbox.test.service_with_oneof_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.HelloAgainResponse)
  })
_sym_db.RegisterMessage(HelloAgainResponse)

_SIMPLEONEOFSERVICE = DESCRIPTOR.services_by_name['SimpleOneOfService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOAGAINREQUEST._serialized_start=55
  _HELLOAGAINREQUEST._serialized_end=92
  _HELLOAGAINRESPONSE._serialized_start=94
  _HELLOAGAINRESPONSE._serialized_end=161
  _SIMPLEONEOFSERVICE._serialized_start=163
  _SIMPLEONEOFSERVICE._serialized_end=264
# @@protoc_insertion_point(module_scope)
