# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/service_with_imported_io.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from sandbox.test import delta_pb2 as sandbox_dot_test_dot_delta__pb2
from sandbox.test import beta_pb2 as sandbox_dot_test_dot_beta__pb2
from sandbox.test import alpha_pb2 as sandbox_dot_test_dot_alpha__pb2
from sandbox.test import nested_pb2 as sandbox_dot_test_dot_nested__pb2
from sandbox.test import rainbow_pb2 as sandbox_dot_test_dot_rainbow__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+sandbox/test/service_with_imported_io.proto\x12\x0csandbox.test\x1a\x18sandbox/test/delta.proto\x1a\x17sandbox/test/beta.proto\x1a\x18sandbox/test/alpha.proto\x1a\x19sandbox/test/nested.proto\x1a\x1asandbox/test/rainbow.proto\x1a\x19google/protobuf/any.proto\x1a\x1fgoogle/protobuf/timestamp.proto2\xf0\x03\n!ServiceWithImportedInputAndOutput\x12>\n\x06Simple\x12\x1a.sandbox.test.DeltaMessage\x1a\x18.sandbox.test.SubMessage\x12\x41\n\x06Nested\x12\x1c.sandbox.test.RainbowMessage\x1a\x19.sandbox.test.BetaMessage\x12>\n\x06Renest\x12\x1a.sandbox.test.OuterMessage\x1a\x18.sandbox.test.SubMessage\x12I\n\x0bTimestampIn\x12\x1e.sandbox.test.TimestampMessage\x1a\x1a.sandbox.test.AlphaMessage\x12\x46\n\x0cTimestampOut\x12\x1a.sandbox.test.AlphaMessage\x1a\x1a.google.protobuf.Timestamp\x12\x39\n\x05\x41nyIn\x12\x14.google.protobuf.Any\x1a\x1a.sandbox.test.AlphaMessage\x12:\n\x06\x41nyOut\x12\x1a.sandbox.test.AlphaMessage\x1a\x14.google.protobuf.Anyb\x06proto3')



_SERVICEWITHIMPORTEDINPUTANDOUTPUT = DESCRIPTOR.services_by_name['ServiceWithImportedInputAndOutput']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SERVICEWITHIMPORTEDINPUTANDOUTPUT._serialized_start=254
  _SERVICEWITHIMPORTEDINPUTANDOUTPUT._serialized_end=750
# @@protoc_insertion_point(module_scope)
