# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sandbox/test/timeduration.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fsandbox/test/timeduration.proto\x12\x0csandbox.test\x1a\x1egoogle/protobuf/duration.proto\"\x92\x02\n\x0f\x44urationMessage\x12.\n\x0bmy_duration\x18\x01 \x01(\x0b\x32\x19.google.protobuf.Duration\x12\x33\n\x10my_duration_list\x18\x02 \x03(\x0b\x32\x19.google.protobuf.Duration\x12I\n\x0fmy_duration_map\x18\x03 \x03(\x0b\x32\x30.sandbox.test.DurationMessage.MyDurationMapEntry\x1aO\n\x12MyDurationMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.google.protobuf.Duration:\x02\x38\x01\x62\x06proto3')



_DURATIONMESSAGE = DESCRIPTOR.message_types_by_name['DurationMessage']
_DURATIONMESSAGE_MYDURATIONMAPENTRY = _DURATIONMESSAGE.nested_types_by_name['MyDurationMapEntry']
DurationMessage = _reflection.GeneratedProtocolMessageType('DurationMessage', (_message.Message,), {

  'MyDurationMapEntry' : _reflection.GeneratedProtocolMessageType('MyDurationMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _DURATIONMESSAGE_MYDURATIONMAPENTRY,
    '__module__' : 'sandbox.test.timeduration_pb2'
    # @@protoc_insertion_point(class_scope:sandbox.test.DurationMessage.MyDurationMapEntry)
    })
  ,
  'DESCRIPTOR' : _DURATIONMESSAGE,
  '__module__' : 'sandbox.test.timeduration_pb2'
  # @@protoc_insertion_point(class_scope:sandbox.test.DurationMessage)
  })
_sym_db.RegisterMessage(DurationMessage)
_sym_db.RegisterMessage(DurationMessage.MyDurationMapEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DURATIONMESSAGE_MYDURATIONMAPENTRY._options = None
  _DURATIONMESSAGE_MYDURATIONMAPENTRY._serialized_options = b'8\001'
  _DURATIONMESSAGE._serialized_start=82
  _DURATIONMESSAGE._serialized_end=356
  _DURATIONMESSAGE_MYDURATIONMAPENTRY._serialized_start=277
  _DURATIONMESSAGE_MYDURATIONMAPENTRY._serialized_end=356
# @@protoc_insertion_point(module_scope)
